# 中国学科分类中英文映射表
# 格式：英文名（不含编号前缀）→ 中文名

SUBJECT_MAP = {
    # 一级学科
    "Philosophy": "哲学",
    "Economics": "经济学",
    "Law": "法学",
    "Education": "教育学",
    "Literature": "文学",
    "History": "历史学",
    "Natural Sciences": "理学",
    "Engineering": "工学",
    "Agriculture": "农学",
    "Medicine": "医学",
    "Management": "管理学",
    "Arts": "艺术学",
    "Military Science": "军事学",

    # 经济学二级
    "Theoretical Economics": "理论经济学",
    "Applied Economics": "应用经济学",
    "International Economics": "国际经济学",
    "Regional Economics": "区域经济学",
    "Finance": "金融学",
    "National Economics": "国民经济学",
    "Financial Science and Engineering": "金融工程",
    "Finance Technology": "金融科技",
    "Quantitative Economics": "数量经济学",
    "Insurance": "保险学",
    "Investment Science": "投资学",
    "Quantitative Finance": "量化金融",

    # 法学二级
    "Theoretical Jurisprudence": "理论法学",
    "Legal History": "法律史",
    "Constitutional Law": "宪法学",
    "Administrative Law": "行政法学",
    "Criminal Law": "刑法学",
    "Civil Law": "民法学",
    "Commercial Law": "商法学",
    "Economic Law": "经济法学",
    "Environmental and Resource Protection Law": "环境与资源保护法学",
    "Procedural Law": "诉讼法学",
    "Economic Management Law": "经济管理法",
    "Labor and Social Security Law": "劳动与社会保障法学",
    "Commercial Organization Law": "商业组织法",
    "Maritime Law": "海商法学",
    "Intellectual Property Law": "知识产权法学",
    "Tax Law": "税法学",
    "Law": "法学",
    "Political Science": "政治学",
    "Sociology": "社会学",
    "Ethnology": "民族学",
    "Marxist Theory": "马克思主义理论",
    "Public Security Studies": "公安学",
    "Science of Socialism": "科学社会主义",
    "History of Communist Party": "中共党史",
    "Marxist Basic Principles": "马克思主义基本原理",
    "Ideological and Political Education": "思想政治教育",
    "Chinese Modern History": "中国近现代史",
    "Foreign Constitutional Law": "外国宪法与行政法",

    # 教育学二级
    "Education Economics": "教育经济学",
    "Education Management": "教育管理学",
    "History of Education": "教育史",
    "Comparative Education": "比较教育学",
    "Pedagogy": "教育学原理",
    "Curriculum and Teaching Methodology": "课程与教学论",
    "Education Technology": "教育技术学",
    "Higher Education": "高等教育学",
    "Adult Education": "成人教育学",
    "Vocational Education": "职业技术教育学",
    "General Education": "基础教育的全面深化改革",
    "Psychology": "心理学",
    "Physical Education": "体育学",
    "Sports Humanities and Sociology": "体育人文社会学",
    "Sports Training": "运动训练学",
    "Sports Humanities": "体育人文社会学",

    # 文学二级
    "Chinese Language and Literature": "中国语言文学",
    "Foreign Languages and Literatures": "外国语言文学",
    "Journalism and Communication": "新闻传播学",
    "Linguistics and Applied Linguistics": "语言学及应用语言学",
    "Chinese Philology": "汉语言文字学",
    "Ancient Chinese Literature": "中国古代文学",
    "Modern and Contemporary Chinese Literature": "中国现当代文学",
    "Comparative Literature and World Literature": "比较文学与世界文学",
    "Literary Theory": "文学理论",
    "Applied Linguistics": "应用语言学",
    "Foreign Linguistics and Applied Linguistics": "外国语言学及应用语言学",
    "English Language and Literature": "英语语言文学",
    "French Language and Literature": "法语语言文学",
    "German Language and Literature": "德语语言文学",
    "Japanese Language and Literature": "日语语言文学",
    "Russian Language and Literature": "俄语语言文学",
    "Spanish Language and Literature": "西班牙语语言文学",
    "Arabic Language and Literature": "阿拉伯语语言文学",

    # 理学二级
    "Mathematics": "数学",
    "Physics": "物理学",
    "Chemistry": "化学",
    "Astronomy": "天文学",
    "Geography": "地理学",
    "Atmospheric Sciences": "大气科学",
    "Oceanography": "海洋科学",
    "Geophysics": "地球物理学",
    "Geology": "地质学",
    "Biology": "生物学",
    "Systems Science": "系统科学",
    "History of Science and Technology": "科学技术史",
    "Ecology": "生态学",
    "Statistics": "统计学",
    "Mechanics": "力学",
    "Materials Science": "材料科学",
    "Information and Communication Engineering": "信息与通信工程",
    "Control Science and Engineering": "控制科学与工程",
    "Computer Science and Technology": "计算机科学与技术",
    "Software Engineering": "软件工程",
    "Network Engineering": "网络工程",
    "Information Security": "信息安全",
    "Data Science and Big Data Technology": "数据科学与大数据技术",
    "Artificial Intelligence": "人工智能",

    # 工学二级
    "Mechanical Engineering": "机械工程",
    "Optical Engineering": "光学工程",
    "Instrument Science and Technology": "仪器科学与技术",
    "Materials Science and Engineering": "材料科学与工程",
    "Metallurgical Engineering": "冶金工程",
    "Power Engineering and Engineering Thermophysics": "动力工程及工程热物理",
    "Electrical Engineering": "电气工程",
    "Electronics Science and Technology": "电子科学与技术",
    "Information and Communication Engineering": "信息与通信工程",
    "Control Science and Engineering": "控制科学与工程",
    "Computer Science and Technology": "计算机科学与技术",
    "Architecture": "建筑学",
    "Civil Engineering": "土木工程",
    "Water Resources Engineering": "水利工程",
    "Surveying and Mapping": "测绘科学与技术",
    "Chemical Engineering and Technology": "化学工程与技术",
    "Geological Resources and Engineering": "地质资源与地质工程",
    "Mining Engineering": "矿业工程",
    "Petroleum and Natural Gas Engineering": "石油与天然气工程",
    "Textile Science and Engineering": "纺织科学与工程",
    "Light Industry Technology and Engineering": "轻工技术与工程",
    "Transportation Engineering": "交通运输工程",
    "Naval Architecture and Ocean Engineering": "船舶与海洋工程",
    "Aerospace Science and Technology": "航空宇航科学与技术",
    "Ordnance Science and Technology": "兵器科学与技术",
    "Nuclear Science and Technology": "核科学与技术",
    "Agricultural Engineering": "农业工程",
    "Forestry Engineering": "林业工程",
    "Environmental Science and Engineering": "环境科学与工程",
    "Biomedical Engineering": "生物医学工程",
    "Food Science and Engineering": "食品科学与工程",
    "Urban and Rural Planning": "城乡规划学",
    "Landscape Architecture": "风景园林学",
    "Bioengineering": "生物工程",
    "Safety Science and Engineering": "安全科学与工程",
    "Public Security Technology": "公安技术",
    "Cyberspace Security": "网络空间安全",
    "Software Engineering": "软件工程",
    "Immunology": "免疫学",
    "Pathology and Pathophysiology": "病理学与病理生理学",

    # 农学二级
    "Crop Science": "作物学",
    "Horticulture": "园艺学",
    "Agricultural Resources and Environment": "农业资源与环境",
    "Plant Protection": "植物保护",
    "Animal Science": "畜牧学",
    "Veterinary Medicine": "兽医学",
    "Forestry": "林学",
    "Fisheries": "水产",
    "Grassland Science": "草学",
    "Agricultural Economics and Management": "农业经济管理",
    "Agricultural Extension": "农业推广",

    # 医学二级
    "Basic Medicine": "基础医学",
    "Clinical Medicine": "临床医学",
    "Stomatology": "口腔医学",
    "Public Health and Preventive Medicine": "公共卫生与预防医学",
    "Traditional Chinese Medicine": "中医学",
    "Integrated Traditional Chinese and Western Medicine": "中西医结合",
    "Pharmacy": "药学",
    "Chinese Materia Medica": "中药学",
    "Specialty Medicine": "特种医学",
    "Medical Technology": "医学技术",
    "Nursing": "护理学",
    "Oncology": "肿瘤学",
    "Neurology": "神经病学",
    "Cardiology": "心血管病学",
    "Infectious Diseases": "传染病学",
    "Gerontology": "老年医学",
    "Pediatrics": "儿科学",
    "Obstetrics and Gynecology": "妇产科学",
    "Surgery": "外科学",
    "Ophthalmology": "眼科学",
    "Otorhinolaryngology": "耳鼻咽喉科学",
    "Dermatology and Venereology": "皮肤病与性病学",
    "Radiology": "影像医学与核医学",
    "Anesthesiology": "麻醉学",
    "Emergency Medicine": "急诊医学",
    "Rehabilitation Medicine": "康复医学与理疗学",
    "Acupuncture and Moxibustion": "针灸推拿学",
    "Ethnopharmacology": "民族药学",
    "Pharmaceutical Analysis": "药物分析学",
    "Pharmaceutical Chemistry": "药物化学",
    "Microbiology and Biochemical Pharmacy": "微生物与生化药学",
    "Pharmaceutics": "药剂学",
    "Pharmacology": "药理学",

    # 管理学二级
    "Management Science and Engineering": "管理科学与工程",
    "Business Administration": "工商管理",
    "Agricultural and Forestry Economics and Management": "农林经济管理",
    "Public Administration": "公共管理",
    "Library, Information and Archives Management": "图书情报与档案管理",
    "Tourism Management": "旅游管理",
    "Real Estate Management": "物业管理",
    "Engineering Management": "工程管理",
    "Information Management": "信息管理与信息系统",
    "Healthcare Management": "卫生事业管理",
    "Educational Economy and Management": "教育经济与管理",
    "National Economy Management": "国民经济管理",
    "Regional Economy Management": "区域经济管理",
    "Urban Economy Management": "城市经济管理",
    "Finance Management": "财务管理",
    "Human Resource Management": "人力资源管理",
    "Marketing Management": "市场营销管理",
    "Operations Management": "运营管理",
    "Supply Chain Management": "供应链管理",
    "E-commerce": "电子商务",
    "Intellectual Property Management": "知识产权管理",

    # 艺术学二级
    "Art Theory": "艺术学理论",
    "Music and Dance": "音乐与舞蹈学",
    "Theater, Film and Television": "戏剧与影视学",
    "Fine Arts": "美术学",
    "Design": "设计学",
    "Drama and Film Studies": "戏剧戏曲学",
    "Musicology": "音乐学",
    "Art Design": "艺术设计",
    "Broadcasting and Television Art": "广播电视艺术学",
    "Dance Studies": "舞蹈学",
    "Film Studies": "电影学",
    "Moral Education": "道德教育",
    "Aesthetic Education": "美学教育",

    # 历史学二级
    "Archaeology": "考古学",
    "Chinese History": "中国史",
    "World History": "世界史",
    "Museology": "博物馆学",
    "Historical Theory": "史学理论",
    "Historical Philology": "史学研究法",
    "Special Histories": "专门史",
    "Chinese Ancient History": "中国古代史",
    "Modern and Contemporary Chinese History": "中国近现代史",
    "World History": "世界史",
    "Historical Geography": "历史地理学",
    "Historical Literature": "历史文献学",
    "Vietnamese History": "越南历史",
}

def translate_name(name: str) -> str:
    """
    将英文目录名翻译为中文。
    输入例如：'02_Economics' 或 '0202_Applied_Economics'
    输出例如：'经济学' 或 '应用经济学'
    如果不在映射表中，返回原名（英文）
    """
    # 去掉编号前缀（01_, 0201_, 0201_ 等）
    parts = name.split("_", 1)
    if len(parts) < 2:
        return name
    # 目录名使用下划线分隔，映射表用空格，统一转为空格后查找
    english_name = parts[1].replace("_", " ")
    return SUBJECT_MAP.get(english_name, parts[1])
